FROM mcr.microsoft.com/dotnet/sdk:5.0 as build-env
WORKDIR /src
EXPOSE 80

COPY ./Webapi/*.csproj /src/Webapi/
WORKDIR /src/Webapi
RUN dotnet restore

WORKDIR /src
COPY . .
WORKDIR /src/Webapi
RUN dotnet publish -c Release -o /src/out/   

FROM mcr.microsoft.com/dotnet/aspnet:5.0 as final-env
WORKDIR /app
COPY --from=build-env /src/out .   
ENTRYPOINT ["dotnet", "Webapi.dll"]
